services:
  datababase:
    # image: postgres:18-alpine
    image: pgvector/pgvector:pg18-trixie
    environment:
      - POSTGRES_PASSWORD=youtube
      - POSTGRES_USER=youtube
      - POSTGRES_DB=youtube
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
